### ISSUE TITLE
Links are broken???

### ISSUE THREAD

**Issue by DeepDiver1975** [groupon/DotCi#100]
```yaml
# image: deepdiver/owncloud-dotci:latest
image: build/docker/dotci/Dockerfile

command:
    php-syntax: find . -name \\*.php -exec php -l "{}" \\;
    sqlite: ./autotest.sh sqlite
    mysql: ./autotest.sh mysql
#    pgsql: ./autotest.sh pgsql
    javascript: ./autotest-js.sh

links: 
  - image: mysql
#  - image: postgres
#  - image: alexeiled/docker-oracle-xe-11g

```

https://ci.owncloud.org/job/owncloud/job/core/93/command=php-syntax/console
````
null
Building remotely on vm-slave-02 (SLAVE docker) in workspace /var/jenkins/workspace/owncloud/core@2/command=php-syntax
[command=php-syntax] $ /bin/bash -le /tmp/hudson867952499301575029.sh
$  docker run -d --name mysql_549442dee4b0309a932c1fc32014-12-23_17-21-25 mysql
9f5db5cbd71060050f8ea685c6bcc25fab3d224d29af0fd480801a2198475744
2014/12/23 23:21:27 Error response from daemon: Cannot start container 9f5db5cbd71060050f8ea685c6bcc25fab3d224d29af0fd480801a2198475744: Cannot find child for /mysql_549442dee4b0309a932c1fc32014-12-23_17-21-25
Build step 'Execute shell' marked build as failure
[command=php-syntax] $ /bin/bash -le /tmp/hudson6511513058924439784.sh
Started calculate disk usage of build
Disk usage plugin fails during calculation disk usage of this build.
Finished: FAILURE
