### ISSUE TITLE
unable to pass computed values to downstream_job parameters

### ISSUE THREAD

**Issue by vvitayau** [groupon/DotCi#150]
downstream_job can pass parameters whose values are hardcoded or setup in the DotCi job's /configure.

It is unable to pass new values computed in the job.
```
build:
  run:
    - export foo="bar"

plugins:
  - downstream_job:
      on_result: 'success'
      a/b:
        BRANCH: "master"
        foo: "${foo}"
```
I expect http://xxx/job/a/job/b/&lt;build number&gt;/parameters to show __bar__ not __$foo__
