### ISSUE TITLE
downstream job unable to access jenkins variable

### ISSUE THREAD

**Issue by vvitayau** [groupon/DotCi#228]
DotCi is not able access https://wiki.jenkins-ci.org/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-JenkinsSetEnvironmentVariables

Based on the following .ci.yml
```
plugins:
  - downstream_job:
      on_result: SUCCESS
      foo/bar:
        VERSION: <% out<< printf("%06d", BUILD_NUMBER.toInteger()) << "-" << DOTCI_SHA.substring(0,10) %>
        BRANCH: master
```

Resulted in null
![screen shot 2016-03-11 at 4 29 46 pm](https://cloud.githubusercontent.com/assets/566629/13717366/968ddb08-e7a6-11e5-9902-2ec663da753b.png)

Aside from groovy script, there is not any other way to compute values since bash commands will not work when outside of the build run section.
