### ISSUE TITLE
Abstract out language_versions into arbitary set of packages

### ISSUE THREAD

**Issue by vvitayau** [groupon/DotCi#24]
Currently we support arbitrary naming of build execution

```
build:
  run:
     A:
       - do step A1..n
     B:
       - do step B1..n
```

We should support the same for packages ... to do away with the concept of language_versions. This will help support key differences between package dependency dependent on the language version rather than force to share the same commonality.
And this alteration does not interrupt the current inherited default use of language defined by https://github.com/groupon/DotCi/blob/master/src/main/resources/com/groupon/jenkins/buildconfiguration/base_yml/language

```
environment:
  language: ruby
  packages:
    A:
    - ruby-1.9.3_p484
    - some lib only required by ruby-1.9.x

    B:
     - ruby-2.x
     - some lib only required by ruby-2.xx
```
